AllCops:
  TargetRubyVersion: 2.4

  Exclude:
    - "**/node_modules/**/*"
    - "bin/*"
    - "db/schema.rb"
    - "vendor/**/*"


Bundler/OrderedGems:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 24

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ModuleLength:
  Max: 500

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/BlockLength:
  Enabled: false

Style/Alias:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Layout/IndentFirstArrayElement:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OptionHash:
 Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Layout/SpaceAroundBlockParameters:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/SpaceInsideReferenceBrackets:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/TrailingBlankLines:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false
